// secure-ref Configuration
// Generated by: npx secure-ref init

import secureRef from 'secure-ref';

export const securityConfig = {
  // Choose your mode (dev / production / strict)
  mode: (process.env.NODE_ENV === 'production' ? 'production' : 'dev') as const,

  // Or force a mode:
  // mode: 'strict',        // best for banking/finance apps

  // Override specific headers if needed
  csp: "default-src 'self'; script-src 'self' 'nonce-'",
  hsts: true,
  frameOptions: 'DENY',
  removeServer: true,
};

// Usage in your server:
export const applySecurity = secureRef(securityConfig);
