#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { analyzeProject } from './analyzer.js';

const command = process.argv[2] || 'help';

console.log('🔒 secure-ref CLI v1.4.0\n');

switch (command) {
    case 'init':
        createConfig();
        break;

    case 'analyze':
        analyzeProject();
        break;

    case 'help':
    default:
        showHelp();
        break;
}

function createConfig() {
    const configPath = path.join(process.cwd(), 'security.config.ts');

    if (fs.existsSync(configPath)) {
        console.log('⚠️  security.config.ts already exists. Not overwriting.');
        return;
    }

    const template = `// secure-ref Configuration
// Generated by: npx secure-ref init

import secureRef from 'secure-ref';

export const securityConfig = {
  // Choose your mode (dev / production / strict)
  mode: (process.env.NODE_ENV === 'production' ? 'production' : 'dev') as const,

  // Or force a mode:
  // mode: 'strict',        // best for banking/finance apps

  // Override specific headers if needed
  csp: "default-src 'self'; script-src 'self' 'nonce-'",
  hsts: true,
  frameOptions: 'DENY',
  removeServer: true,
};

// Usage in your server:
export const applySecurity = secureRef(securityConfig);
`;

    fs.writeFileSync(configPath, template, 'utf8');

    console.log('✅ Created security.config.ts');
    console.log('📁 Location: ./security.config.ts');
    console.log('\nNext steps:');
    console.log('1. Import it in your server:');
    console.log('   import { applySecurity } from "./security.config";');
    console.log('   app.use(applySecurity);');
    console.log('2. Run in production: NODE_ENV=production node server.js');
}

function showHelp() {
    console.log('Usage: npx secure-ref <command>');
    console.log('');
    console.log('Commands:');
    console.log('  init     → Create security.config.ts with Smart Modes');
    console.log('  analyze  → Run a security check & score your project');
    console.log('  help     → Show this help');
    console.log('');
    console.log('More commands coming in v2 (audit...)');
}
